Qshop/Buyer/urls.py
from django.urls import path,re_path
from Buyer.views import *
urlpatterns = [
    path('register/',register),
    path('login/',login),
    path('index/',index),
    path('goods_list/',goods_list),
    re_path('goods_detail/(?P<id>\d+)/',goods_detail),
    path('user_info/',user_info),
    path('add_cart/',add_cart),
    path('cart/',cart),
    path('pay_order/',pay_order),
    path('pay_order_more/',pay_order_more),
    path('pay_result/',pay_result),
    path('alipay/',AliPayViews),

]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Seller/',include("Seller.urls")),
    path('Buyer/',include("Buyer.urls")),
]

Qshop/Buyer/models.py
from django.db import models
from Seller.models import LoginUser
from django.db.models import Manager

class PayOrder(models.Model):
    order_number = models.CharField(max_length=32)
    order_data = models.DateTimeField(auto_now=True)

    order_total = models.FloatField(blank=True,null=True)
    order_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)

class OrderInfo(models.Model):
    """
    订单详情表
    """
    order_id = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE)
    goods_id = models.IntegerField()
    goods_picture = models.CharField(max_length=32)
    goods_name = models.CharField(max_length=32)
    goods_count = models.IntegerField()
    goods_price = models.FloatField()
    goods_total_price = models.FloatField()
    order_status = models.IntegerField(default=0)
    store_id = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)

class CartManage(Manager):
    def adds(self,id):
        cart = Cart.objects.get(id=id)
        cart.goods_numbebr += 1
        cart.goods_total += cart.goods_price
        cart.save()

class Cart(models.Model):
    goods_name = models.CharField(max_length=32)
    goods_number = models.IntegerField()
    goods_price = models.FloatField()
    goods_picture = models.CharField(max_length=32)
    goods_total = models.FloatField()
    goods_id = models.IntegerField()
    cart_user = models.IntegerField()

    objects = CartManage()
# Create your models here.

Qshop/Buyer/views.py
import hashlib
import time,datetime
from Buyer.models import *
from Seller.models import *
from alipay import AliPay
from Seller.views import setPassword
from django.http import JsonResponse
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from Qshop.settings import alipay_public_key_string,alipay_private_key_string
def LoginValid(fun):
    def inner(request,*args,**kwargs):
        cookie_user = request.COOKIES.get("username")
        session_user = request.session.get("username")
        if cookie_user and session_user and cookie_user == session_user:
            return fun(request,*args,**kwargs)
        else:
            return HttpResponseRedirect("Buyer/login/")
    return inner
def register(request):
    if request.method == 'POST':
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        db_password = request.POST.get('cpwd')
        if password == db_password:
            user = LoginUser()
            user.username = username
            user.password = setPassword(password)
            user.email = email
            user.save()
            return HttpResponseRedirect('/Buyer/login/')
    return render(request,'buyer/register.html',locals())
def login(request):
    if request.method == "POST":
        password = request.POST.get("pwd")
        email = request.POST.get("email")
        user = LoginUser.objects.filter(email=email).first()
        if user:
            db_password = user.password
            password = setPassword(password)
            if db_password == password:
                response = HttpResponseRedirect('/Buyer/index/')
                response.set_cookie('username',user.username)
                response.set_cookie('user_id',user.id)
                response.set_cookie('email',user.email)
                request.session['username'] = user.username
                return response
    return render(request,'buyer/login.html',locals())
def index(request):
    goods_type = GoodsType.objects.all()
    result = []
    for ty in goods_type:
        goods = ty.goods_set.order_by("-goods_pro_time")
        if len(goods)>4:
            goods = goods[:4]
            result.append({"type":ty,"goods_list":goods})
            print(result)
    return render(request,'buyer/index.html',locals())

def goods_list(request):
    request_type = request.GET.get("type")
    keyword = request.GET.get("keywords")
    goods_list = []
    if request_type == "t":
        if keyword:
            id = int(keyword)
            goods_type = GoodsType.objects.get(id = id)
            goods_list = goods_type.goods_set.order_by("-goods_pro_time")
    elif  request_type == "k":
        if keyword:
            goods_list = Goods.objects.filter(goods_name__contains=keyword).order_by("-goods_pro_time")
    #买家页面分页功能
    if goods_list:
        lenth = len(goods_list) / 5
        if lenth != int(lenth):
            lenth += 1
        lenth = int(lenth)
        recommend = goods_list[:lenth]
    return render(request,"buyer/goods_list.html",locals())

def goods_detail(request,id):
    goods = Goods.objects.get(id = int(id))
    return render(request,"buyer/detail.html",locals())

@LoginValid
def user_info(request):
    return render(request,"buyer/user_info.html",locals())



@LoginValid
def add_cart(request):
    result = {
        "code":200,
        "data":""
    }
    if request.method == "POST":
        id = int(request.POST.get("goods_id"))
        count = int(request.POST.get("count",1))

        goods = Goods.objects.get(id=id)#获取商品信息
        cart = Cart()
        cart.goods_name = goods.goods_name
        cart.goods_number = count
        cart.goods_price = goods.goods_price
        cart.goods_picture = goods.picture
        cart.goods_total = goods.goods_price*count
        cart.goods_id = id
        cart.cart_user = request.COOKIES.get("user_id")
        cart.save()
        result["data"] = "加入购物车成功"
    else:
        result["code"] = 500
        result["data"] = "请求方式错误"
    return JsonResponse(result)

def cart(request):
    user_id = request.COOKIES.get("user_id")
    goods = Cart.objects.filter(cart_user=int(user_id))
    count = goods.count()
    return render(request,"buyer/cart.html",locals())


@LoginValid
def pay_order(request):
    goods_id = request.GET.get("goods_id")
    count = request.GET.get("count")
    if goods_id and count:
        # 保存订单表，保存总价
        order = PayOrder()
        order.order_number = str(time.time()).replace(".", "")
        order.order_data = datetime.datetime.now()
        order.order_user = LoginUser.objects.get(id=int(request.COOKIES.get("user_id")))  # 订单对应的买家
        order.save()
        # 保存订单详情
        # 查询商品的信息
        goods = Goods.objects.get(id=int(goods_id))
        order_info = OrderInfo()
        order_info.goods_id = goods_id
        order_info.goods_picture = goods.picture
        order_info.goods_name = goods.goods_name
        order_info.goods_count = int(count)
        order_info.goods_price = goods.goods_price
        order_info.goods_total_price = goods.goods_price * int(count)
        order_info.store_id = goods.goods_store
        order_info.save()
        order.order_total = order_info.goods_total_price
        order.save()
    return render(request, "buyer/pay_order.html", locals())


@LoginValid
def pay_order_more(request):
    data = request.GET
    data_item = data.items()
    request_data = []
    for key, value in data_item:
        if key.startswith("check_"):
            goods_id = key.split("_", 1)[1]
            count = data.get("count_" + goods_id)
            request_data.append((int(goods_id), int(count)))
    if request_data:
        # 保存订单表，但是保存总价
        order = PayOrder()
        order.order_number = str(time.time()).replace(".", "")
        order.order_data = datetime.datetime.now()
        order.order_user = LoginUser.objects.get(id=int(request.COOKIES.get("user_id")))
        order.save()
        # 保存订单详情
        # 查询商品的信息
        order_total = 0
        for goods_id, count in request_data:
            print(goods_id, count)
            goods = Goods.objects.get(id=int(goods_id))

            order_info = OrderInfo()
            order_info.order_id = order
            order_info.goods_id = goods_id
            order_info.goods_picture = goods.picture
            order_info.goods_name = goods.goods_name
            order_info.goods_count = int(count)
            order_info.goods_price = goods.goods_price
            order_info.goods_total_price = goods.goods_price*int(count)
            order_info.store_id = goods.goods_store#商品卖家，goods.good_store本身就是一条卖家信息
            order_info.save()
            order_total += order_info.goods_total_price
        order.order_total = order_total
        order.save()
    return render(request, 'buyer/pay_order.html', locals())


def AliPayViews(request):
    order_number = request.GET.get("order_number")
    order_total = request.GET.get("order_total")
    # 实例化支付
    alipay = AliPay(
        appid="2016101200667752",
        app_notify_url=None,
        app_private_key_string=alipay_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2"
    )

    # 实例化订单
    order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no=order_number,  # 订单号
        total_amount=str(order_total),  # 支付金额  字符串
        subject="生鲜交易",  # 支付主题
        return_url="http://127.0.0.1:8000/Buyer/pay_result/",
        notify_url="http://127.0.0.1:8000/Buyer/pay_result/"
    )  # 网页支付订单
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    return HttpResponseRedirect(result)


def pay_result(request):
    out_trade_no = request.GET.get("out_trade_no")
    if out_trade_no:
        order = PayOrder.objects.get(order_number=out_trade_no)
        order.order_status = 1
        order.save()
    return render(request, 'buyer/pay_result.html', locals())

# Create your views here.

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
                {% if request.COOKIES.email %}
				    <div class="login_btn fl">
                        <a href="/Buyer/login/">欢迎</a>
                        <span>|</span>
                        <a href="/Buyer/logout/">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/Buyer/login/">登录</a>
                        <span>|</span>
                        <a href="/Buyer/register/">注册</a>
                    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/Buyer/user_info/">用户中心</a>
					<span>|</span>
					<a href="/Buyer/cart/">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input id="search_key"type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="search()">
		</div>
		<div class="guest_cart fr">
			<a href="/Buyer/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {% block content %}
    {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block script %}
    {% endblock %}
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
	<script type="text/javascript">
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');
		var hasorder = localStorage.getItem('order_finish');
		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}
		function search() {
            var keyword = $("#search_key").val();
            if (keyword){
                var url = "/Buyer/goods_list/?type=k&keywords="+keyword;
                window.location.href = url
            }
        }
	</script>
</body>
</html>

Qshop/Buyer/templates/buyer/cart.html
{% extends "buyer/base.html" %}
{% block title %}
    购物车
{% endblock %}
{% block content %}
    <div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/Buyer/pay_order_more/">
    {% for g in goods %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" class="goods_check" name="check_{{ g.goods_id }}" checked></li>
		<li class="col02"><img src="/static/{{ g.goods_picture }}"></li>
		<li class="col03">{{ g.goods_name }}<br><em>{{ g.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ g.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ g.goods_number }}" name="count_{{ g.goods_id }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ g.goods_total }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}



	<ul class="settlements">
		<li class="col01"><input type="checkbox" id="allbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ goods_total }}</em><br>共计<b>{{ count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
{% endblock %}
</form>

{% block script %}
    <script>
        $("#allbox").click(
            function () {
                if (this.checked){
                    $(".goods_check").prop("checked",true)
                }else{
                    $(".goods_check").prop("checked",false)
                }
            }
        );
        $(".goods_check").each(
            function () {
                $(this).click(
                    function () {
                        if(!this.checked){
                            $("#allbox").prop("checked",false)
                        }
                    }
                )
            }
        )
    </script>
{% endblock %}

{#{% block script %}#}
{#    <script>#}
{#        $("#allbox").click(#}
{#            function () {#}
{#                if(this.checked){#}
{#                    $(".checkbox").prop("checked",true)#}
{#                }else{#}
{#                    $(".checkbox").prop("checked",false)#}
{#                }#}
{#            }#}
{#        );#}
{#        $(".goods_check").each(#}
{#            function () {#}
{#                $(this).click(#}
{#                    function () {#}
{#                        if (!this.checked){#}
{#                            $("#allbox").prop("checked",false)#}
{#                        } #}
{#                    }#}
{#                )#}
{#            }#}
{#        )#}
{#    </script>#}
{#{% endblock %}#}

Qshop/Buyer/templates/buyer/detail.html
{% extends "buyer/base.html" %}

{% block title %}
    商品详情页
{% endblock %}

{% block content %}
    <div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img style="width: 100%;height: 100%;" src="/static/{{ goods.picture }}"></div>
		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_description }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="price">{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input id="number" type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" onclick="adds()">+</a>
					<a href="javascript:;" class="minus fr" onclick="down()">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="total">12.0</em><em>元</em></div>
			<div class="operate_btn">
				<a  href="javascript:;" class="buy_btn" onclick="buy_now()">立即购买</a>
				<a  href="javascript:;" class="add_cart" onclick="add_cart(this)" id="{{ goods.id }}">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>
    {% block script %}
        <script>
                function adds() {
                    console.log("hello world");
                    value = parseInt($("#number").val());
                    price = parseFloat(($("#price")).text());
                    value = value + 1;
                    $("#number").val(value);
                    total = value*price;
                    $("#total").text(total)
                };
                function down() {
                    value = parseInt($("#number").val());
                    price = parseFloat(($("#price")).text());
                    if (value>1){
                        value = value - 1;
                        $("#number").val(value)
                    }else{
                        $("#number").val(1)
                    }
                    total = value*price;
                    $("#total").text(total)
                }
                    function buy_now() {
                        url = "/Buyer/pay_order/?goods_id={{ goods.id }}&count="+$("#number").val();
                        window.location.href = url
                    }
        </script>
        <script>
            function add_cart(obj) {
                var goods_id = obj.id;
                var count = $("#number").val();
                var csrf_token = "{{ csrf_token }}";
                var sendData = {
                    "goods_id":goods_id,
                    "count":count,
                    "csrfmiddlewaretoken":csrf_token
                };
                $.ajax(
                    {
                        url:"/Buyer/add_cart/",
                        type:"post",
                        data:sendData,
                        success:function (data) {
                            alert(data["data"])
                        },
                        error:function (error) {
                            console.log(error)
                        }
                    }
                )
            }
        </script>
    {% endblock %}
{% endblock %}

Qshop/Buyer/templates/buyer/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/buyer/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="email" class="name_input" placeholder="请输入邮箱">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

Qshop/Buyer/templates/buyer/pay_order.html
{% extends "buyer/base.html" %}
{% block title %}
    商品订单
{% endblock %}

{% block content %}
    <div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" >
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" checked>
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
    {% for goods in order.orderinfo_set.all %}
		<ul class="goods_list_td clearfix">
			<li class="col01">1</li>
            <li class="col02"><img src="/static/{{ goods.goods_picture }}"></li>
            <li class="col03">{{ goods.goods_name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ goods.goods_price }}元</li>
			<li class="col06">{{ goods.goods_count }}</li>
			<li class="col07">{{ goods.goods_total_price }}元</li>
		</ul>
    {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>1</em>件商品，总金额<b>{{ order.order_total }}元</b></div>
			<div class="transit">运费：<b>0元</b></div>
			<div class="total_pay">实付款：<b>{{ order.order_total }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="/Buyer/alipay/?order_number={{ order.order_number }}&order_total={{ order.order_total }}" id="order_btn">提交订单</a>
	</div>
{% endblock %}

Qshop/Buyer/templates/buyer/pay_result.html
{% extends 'buyer/base.html' %}

{% block title %}
    支付结果
{% endblock %}

{% block content %}
    <div class="list_model">
        <h1>支付成功</h1>
    </div>
{% endblock %}

Qshop/Buyer/templates/buyer/user_center_order.html
{% extends "buyer/base.html" %}
{% block title %}
    用户订单
{% endblock %}
{% block content %}
    	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/Buyer/user_info/">· 个人信息</a></li>
				<li><a href="/Buyer/uco/" class="active">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for order in order_list %}

				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.order_data }}</li>
					<li class="col02">{{ order.order_number }}</li>
                    {% ifequal order.order_status 0 %}
					<td width="15%">未支付</td>
                    {% endifequal %}
                    {% ifequal order.order_status 1 %}
					<td width="15%">已支付</td>
                    {% endifequal %}
                    {% ifequal order.order_status 2 %}
					<td width="15%">待发货</td>
                    {% endifequal %}
                    {% ifequal order.order_status 3 %}
					<td width="15%">待收货</td>
                    {% endifequal %}
                    {% ifequal order.order_status 4 %}
					<td width="15%">完成</td>
                    {% endifequal %}
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for o in order.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ o.goods_picture }}"></li>
									<li class="col02">{{ o.goods_name }}<em>{{ o.goods_price }}元/500g</em></li>
									<li class="col03">{{ o.goods_count }}</li>
									<li class="col04">{{ o.goods_total_price }}元</li>
								</ul>
                                    {% endfor %}

							</td>

							<td width="15%">{{ order.order_total }}元</td>
                            {% ifequal order.order_status 0 %}
                                <td width="15%"><a href="/Buyer/alipay/?order_number={{ order.order_number }}&order_total={{ order.order_total }}" class=order_btn>去付款</a></td>
                            {% else %}
                                <td width="15%"><a href="#" class="oper_btn">查看详情</a></td>
                            {% endifequal %}

						</tr>
					</tbody>
				</table>
            {% endfor %}



				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}